version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: manishsahu53/cogapi:1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.9"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
